version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:199944304157:task-definition/task-go-rest-sample"
        LoadBalancerInfo:
          ContainerName: "app"
          ContainerPort: 8080